### ISSUE TITLE
I can't change the background image

### ISSUE THREAD

**Issue by ghost** [loadfred/tidy-sddm#1]
I had uncommented and added the full path to my image into the config file, but it didn't seem to work.

I have tried:

* Encasing the path with `"` or `'`.
* Using a path without whitespaces.

**My system info:**

**Distro:** Ultramarine Linux 41
**Desktop:** KDE Plasma 6.2.3

**Comment by loadfred** [comment]
SDDM probably needs permissions to open your home folder, try:
`sudo chmod o+X /home/myuser`

**Comment by ghost** [comment]
> SDDM probably needs permissions to open your home folder, try: `sudo chmod o+X /home/myuser`

I didn't want to give view access to my home folder so I instead created a backgrounds folder in the tidy-sddm themes directory, copied the image there and granted the proper permissions.

It worked as expected now.

**Comment by loadfred** [comment]
I've updated Tidy, you can now change the background in KDE system settings 520d036b1d6ad42630266338ba276821982836aa
(and all theme.conf variables were changed)
Thanks for the issue
